### ISSUE TITLE
问个问题，集成在线上的版本，审核会被拒绝么

### ISSUE THREAD

**Issue by hongdong** [lszzy/FWDebug#1]
问个问题，集成在线上的版本，审核会被拒绝么，线上的版本设置了隐藏的呼出按钮。

**Comment by liman123** [comment]
```
#if DEBUG
  import FWDebug
  //code...
#endif
```

可以参考以上做法.
我也做了一个debug tool, 欢迎多交流哈~
[DebugMan](https://github.com/liman123/DebugMan)

**Comment by lszzy** [comment]
会被拒。调试工具用了私有api。文档里面有说明的
