### ISSUE TITLE
为什么 1.7.0 版本中没有了 真机 NSLog 的功能？

### ISSUE THREAD

**Issue by jaydenin** [lszzy/FWDebug#10]
为什么 1.7.0 版本中没有了 真机 NSLog 的功能？ 同一个项目安装 1.6.0 版本还是有的。

**Comment by lszzy** [comment]
> 为什么 1.7.0 版本中没有了 真机 NSLog 的功能？ 同一个项目安装 1.6.0 版本还是有的。

1.7.0版本因为FLEX3.0自带了NSLog的功能，所以去掉了原来自己实现的NSLog方式。1.7.0版本NSLog开启方式：进入System Log，点击右上角Settings然后弹出的界面选择Enable即可开启NSLog功能。
