### ISSUE TITLE
对wkwebview支持的不够好

### ISSUE THREAD

**Issue by lgq2015** [lszzy/FWDebug#12]

**Comment by lszzy** [comment]
请问能说具体点吗？谢谢
目前对WKWebView的调试功能主要有自动注入vConsole，抓取WKWebView网络请求功能，默认关闭，可以在App Config中开启选项。
vConsole功能比较强大，内置请求抓包等，基本能满足日常开发调试需求。

**Comment by lszzy** [comment]
> No description provided.

请问能说具体点吗？谢谢
目前对WKWebView的调试功能主要有自动注入vConsole，抓取WKWebView网络请求功能，默认关闭，可以在App Config中开启选项。
vConsole功能比较强大，内置请求抓包等，基本能满足日常开发调试需求。
