### ISSUE TITLE
arm64e

### ISSUE THREAD

**Issue by zhang3636** [lszzy/FWDebug#14]
能支持一下arm64e么

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by lszzy** [comment]
> 能支持一下arm64e么
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

arm64e是向下兼容arm64的，没太明白你的使用场景。可以试试clone仓库并修改根目录的Build.sh编译脚本试试，或者提供一个不支持arm64e场景的demo给我？
