### ISSUE TITLE
能把FBRetainCycleDetector剥离出来只做依赖么

### ISSUE THREAD

**Issue by hongdong** [lszzy/FWDebug#3]
和挺多库有冲突的

**Comment by lszzy** [comment]
这个库设计的时候为了方便使用和不依赖三方版本（底层用的swizzle实现，三方版本变了可能会导致不可用），也为了直接编译framework使用，直接引用的源代码。根据你的需求，你可以这样做：fork一份源码，删除Vendor里面的FBRetainCycleDetector，然后修改其他源码里面的FBRetainCycleDetector头文件引用，添加pod依赖就可以了。如果你有需要的调试功能的话，我可以加进来。谢谢支持

**Comment by hongdong** [comment]
感谢回答
